### PR TITLE
changed animationEndSupport to false to fix safari issie

### PR DESCRIPTION
**Pull request by thoughtpalette**
@StoicJester Please review. Thanks!

Related: https://github.com/likeastore/ngDialog/issues/199

### CODE REVIEW

**Comment by StoicJester** [comment]
LGTM

**Comment by StoicJester** [comment]
@scottferg

**Comment by thoughtpalette** [comment]
I ninja merged :octocat:

**Comment by StoicJester** [comment]
⊙▃⊙

**Comment by dmaloneycalu** [comment]
This has been breaking my PRs lately. I've resorted to reloading the page if I want a dialog to go away.

**Comment by thoughtpalette** [comment]
@dmaloneycalu O.o

**Pull request merged**
